// Generated by tools/mf_runtime_public_effects_table.py from
// mirrorforce/mirrorforce/agent/env/public_effects/public-effects-v1.json. Do not edit; regenerate with `write`.
// Included by public_status.h after its Rule, Selector and TargetSide definitions.
#pragma once

namespace duelenv {
namespace public_effects {

inline constexpr const char *kTableSha256 = "f7d0427f3b3c1cbaf253c97df01d2eaea11a4dbb76f3ffc9a2f90fa3c9e26452";

// The cards whose lingering public effects were reviewed (sorted): their rules below, or none.
inline constexpr uint32_t kReviewed[] = {
    2857636u, 5821478u, 8491308u, 14558127u, 23434538u, 24010609u, 25955749u, 26077387u,
    32807846u, 35726888u, 38342335u, 41420027u, 41999284u, 43898403u, 50005218u, 50588353u,
    51227866u, 52340444u, 52340445u, 59438930u, 63166095u, 63288573u, 67441435u, 70368879u,
    73594093u, 75452921u, 84749824u, 85289965u, 90673288u, 97268402u, 97616504u, 98338152u,
    99550630u,
};

// card, description (code * 16 + index; 0 for an activation without one), selector, from and
// to location masks (moved), status bit, player kind, target side, the card must stay at its place
inline constexpr Rule kRules[] = {
    {24010609u, 384169745, Selector::kMoved, 0x10, 0x08, 0x01, 0, TargetSide::kAny, true},  // Sky Striker Mecha Modules - Multirole
    {24010609u, 384169744, Selector::kPlayer, 0x00, 0x00, 0x00, 2, TargetSide::kAny, true},  // Sky Striker Mecha Modules - Multirole
    {51227866u, 0, Selector::kMoved, 0x10, 0x04, 0x02, 0, TargetSide::kAny, false},  // Sky Striker Mecha - Shark Cannon
    {50588353u, 809413648, Selector::kMoved, 0x03, 0x04, 0x04, 0, TargetSide::kAny, false},  // Crystron Halqifibrax
    {97268402u, 1556294432, Selector::kTargets, 0x00, 0x00, 0x08, 0, TargetSide::kOpponent, false},  // Effect Veiler
    {98338152u, 0, Selector::kTargets, 0x00, 0x00, 0x08, 0, TargetSide::kAny, false},  // Sky Striker Mecha - Widow Anchor
    {98338152u, 0, Selector::kControlTaken, 0x00, 0x00, 0x10, 0, TargetSide::kAny, false},  // Sky Striker Mecha - Widow Anchor
    {85289965u, 1364639440, Selector::kSelf, 0x00, 0x00, 0x20, 0, TargetSide::kAny, false},  // Borrelsword Dragon
    {23434538u, 374952608, Selector::kPlayer, 0x00, 0x00, 0x00, 1, TargetSide::kAny, false},  // Maxx "C"
    {5821478u, 93143648, Selector::kPlayer, 0x00, 0x00, 0x00, 3, TargetSide::kAny, false},  // Topologic Bomber Dragon
};

}  // namespace public_effects
}  // namespace duelenv
